#define FORTITUDE_ATTRIBUTE "Fortitude"
#define PRUDENCE_ATTRIBUTE "Prudence"
#define TEMPERANCE_ATTRIBUTE "Temperance"
#define JUSTICE_ATTRIBUTE "Justice"

#define WORK_TO_ATTRIBUTE list(\
							ABNORMALITY_WORK_INSTINCT = FORTITUDE_ATTRIBUTE,\
							ABNORMALITY_WORK_INSIGHT = PRUDENCE_ATTRIBUTE,\
							ABNORMALITY_WORK_ATTACHMENT = TEMPERANCE_ATTRIBUTE,\
							ABNORMALITY_WORK_REPRESSION = JUSTICE_ATTRIBUTE,\
							)
