#define JOB_AVAILABLE 0
#define JOB_UNAVAILABLE_GENERIC 1
#define JOB_UNAVAILABLE_BANNED 2
#define JOB_UNAVAILABLE_PLAYTIME 3
#define JOB_UNAVAILABLE_ACCOUNTAGE 4
#define JOB_UNAVAILABLE_SLOTFULL 5
#define JOB_NOT_TRUSTED 8

#define DEFAULT_RELIGION "Christianity"
#define DEFAULT_DEITY "Space Jesus"

#define JOB_DISPLAY_ORDER_DEFAULT 0

//Command
#define JOB_DISPLAY_ORDER_MANAGER 1
#define JOB_DISPLAY_ORDER_SEPHIRAH 2
#define JOB_DISPLAY_ORDER_COMMAND 3
#define JOB_DISPLAY_ORDER_COMMANDLOWER 4
#define JOB_DISPLAY_ORDER_DEPARTMENTHEAD 5

//Agents
#define JOB_DISPLAY_ORDER_CAPTAIN 7
#define JOB_DISPLAY_ORDER_AGENT 8
#define JOB_DISPLAY_ORDER_INTERN 9

//Not affiliated with LC
#define JOB_DISPLAY_ORDER_HHPP 11
#define JOB_DISPLAY_ORDER_CIVILIAN 12
#define JOB_DISPLAY_ORDER_ANTAG 13
#define JOB_DISPLAY_ORDER_DIRECTOR 14
#define JOB_DISPLAY_ORDER_VETERAN 15
#define JOB_DISPLAY_ORDER_ASSOCIATION 16
#define JOB_DISPLAY_ORDER_FIXER 17

//RP roles
#define JOB_DISPLAY_ORDER_REPRESENTATIVE 18

//Clerk
#define JOB_DISPLAY_ORDER_CLERK 999
