#define JOB_AVAILABLE 0
#define JOB_UNAVAILABLE_GENERIC 1
#define JOB_UNAVAILABLE_BANNED 2
#define JOB_UNAVAILABLE_PLAYTIME 3
#define JOB_UNAVAILABLE_ACCOUNTAGE 4
#define JOB_UNAVAILABLE_SLOTFULL 5
#define JOB_NOT_TRUSTED 8
#define JOB_NOT_MENTOR 9

#define DEFAULT_RELIGION "Christianity"
#define DEFAULT_DEITY "Space Jesus"

#define JOB_DISPLAY_ORDER_DEFAULT 0

#define DEPARTMENT_SECURITY (1<<0)
#define DEPARTMENT_COMMAND (1<<1)
#define DEPARTMENT_SERVICE (1<<2)
#define DEPARTMENT_CARGO (1<<3)
#define DEPARTMENT_ENGINEERING (1<<4)
#define DEPARTMENT_SCIENCE (1<<5)
#define DEPARTMENT_MEDICAL (1<<6)
#define DEPARTMENT_SILICON (1<<7)

//Command
#define JOB_DISPLAY_ORDER_MANAGER 1
#define JOB_DISPLAY_ORDER_SEPHIRAH 2
#define JOB_DISPLAY_ORDER_COMMAND 3
#define JOB_DISPLAY_ORDER_COMMANDLOWER 4
#define JOB_DISPLAY_ORDER_DEPARTMENTHEAD 5

//Agents
#define JOB_DISPLAY_ORDER_CAPTAIN 7
#define JOB_DISPLAY_ORDER_AGENT 8
#define JOB_DISPLAY_ORDER_INTERN 9
#define JOB_DISPLAY_ORDER_SUPPRESSION 10

//Not affiliated with LC
#define JOB_DISPLAY_ORDER_MEDICAL 11
#define JOB_DISPLAY_ORDER_MEDICALASSIST 12
#define JOB_DISPLAY_ORDER_HHPP 13
#define JOB_DISPLAY_ORDER_CIVILIAN 14
#define JOB_DISPLAY_ORDER_ANTAG 15
#define JOB_DISPLAY_ORDER_DIRECTOR 16
#define JOB_DISPLAY_ORDER_VETERAN 17
#define JOB_DISPLAY_ORDER_ASSOCIATION 18
#define JOB_DISPLAY_ORDER_FIXERLEAD 19
#define JOB_DISPLAY_ORDER_FIXER 20

//RP roles
#define JOB_DISPLAY_ORDER_MISC 21
#define JOB_DISPLAY_ORDER_REPRESENTATIVE 22

//Syndicate
#define JOB_DISPLAY_ORDER_SYNDICATEHEAD 23
#define JOB_DISPLAY_ORDER_SYNDICATEVET 24
#define JOB_DISPLAY_ORDER_SYNDICATESUPPORT 25
#define JOB_DISPLAY_ORDER_SYNDICATEGOON 26
#define JOB_DISPLAY_ORDER_SYNDICATEEXTRA 27

//Clerk
#define JOB_DISPLAY_ORDER_CLERK 999
