#define RCE_TARGET_TYPE_GENERIC 1
#define RCE_TARGET_TYPE_FOB_ENTRANCE 2
#define RCE_TARGET_TYPE_LOW_LEVEL 4
#define RCE_TARGET_TYPE_MID_LEVEL 8
#define RCE_TARGET_TYPE_HIGH_LEVEL 16
#define RCE_TARGET_TYPE_XCORP_BASE 32
