/obj/item/storage/belt/medical/surgeryfilled/PopulateContents()
	new /obj/item/scalpel(src)
	new /obj/item/hemostat(src)
	new /obj/item/retractor(src)
	new /obj/item/circular_saw(src)
	new /obj/item/cautery(src)
	new /obj/item/surgical_drapes(src)
